### ISSUE TITLE
https://stackoverflow.com/questions/64198196/i-want-to-drag-window-from-custon-window-title-in-pyqt5

### ISSUE THREAD

**Issue by juniorrao** [Wanderson-Magalhaes/Python_PySide2_Custom_Title_Bar#1]
please help
https://stackoverflow.com/questions/64198196/i-want-to-drag-window-from-custon-window-title-in-pyqt5

**Comment by juniorrao** [comment]
https://stackoverflow.com/questions/64198196/i-want-to-drag-window-from-custon-window-title-in-pyqt5

**Comment by Wanderson-Magalhaes** [comment]
Please detail your question.
This function of moving an application window does not work very well on Linux, on Mac it works with some limitations and on Windows it works correctly, is Qt limitions.

**Comment by juniorrao** [comment]
sir this is my project on which am working i took your concept of frameless window and buttons of mac style from your project custom title bar, as your project is in PySide2 but am working in PyQt5 so all ui_functions worked properly after few changes but this moving an application window is not working, plz once go through my code and help me plz , ignore the extra code in project i have ade that as comment!! by using # .  I watch your videos on youtube too. i have subscribed you on youtube as well.
Reply asap!! Thank You
and sir am btech computer science student(3rd year)  in india , i want to learn this pyqt and qt designer from you!! big fan !! Thank You!!
my mail id is: raoashu672outlook.com

**Comment by Wanderson-Magalhaes** [comment]
Applications works with **Events** (mouveMoveEvent, clicked, mouse drag...), so Add "from PyQt5.QtCore import (Qt, **QEvent**)" and you call wrong "**mouseMoveEvent**"
![image](https://user-images.githubusercontent.com/60605512/95089837-fa8bf900-06fa-11eb-8b2d-31297a85d559.png)

**Comment by juniorrao** [comment]
Thank You So much sir for your help 
it worked 👍 
once again Thankyou:-)
